version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  ngrok:
    image: ngrok/ngrok:3
    ports:
      - "4040:4040"
    command: ["http", "host.docker.internal:9000"]

